import os 
import xlwings as xw
import pandas as pd

path=os.path.dirname(__file__)
print(path)
file_path=os.path.join(path,'purchase_order.xlsx')
print(file_path)
app=xw.App(visible=False,add_book=False) # create a new instance of Excel
wb=app.books.open(file_path) # open the workbook
sheets=wb.sheets # select  all sheet
print(sheets)
table=pd.DataFrame() # create a new DataFrame
for sheet in sheets:
    values=sheet.range('A1').expand('table').options(pd.DataFrame, index=False, header=True).value
    print(values)
    data=values.reindex(columns=['采购物品','采购日期','采购数量','采购金额'])
    print(data)
    table=table._append(data,ignore_index=True)
print("new table")    
print(table)
table=table.groupby('采购物品')
print("new table generated by groupby")
print(table)
new_wb=xw.books.add() # create a new workbook
# for i,group in table:
#     sheet=new_wb.sheets.add(name=i)
#     sheet.range('A1').value=group.to_excel() # write the DataFrame to a new sheet
# new_wb.save(os.path.join(path,'purchase_order_new.xlsx')) # save the new workbook
# new_wb.close() # close the new workbook
# wb.close() # close the original workbook
# app.quit() # quit the Excel instance
# print("done")

for i,group in table:
    new_worksheet=new_wb.sheets.add(name=i)
    new_worksheet.range('A1').options(index=False).value=group
    last_cell=new_worksheet.range('A1').expand('table').last_cell # get the last cell of the table
    last_row=last_cell.row # get the row number of the last cell
    last_column=last_cell.column # get the column number of the last cell
    last_column_letter=chr(64+last_column) # get the column letter of the last column
    print(last_column_letter)
    sum_cell_name='{}{}'.format(last_column_letter, last_row+1) # get the name of the sum cell
    print(sum_cell_name)
    sum_last_row_name='{}{}'.format(last_column_letter, last_row) # get the name of the last row cell
    print(sum_last_row_name)
    formula='=SUM({}2{}:{})'.format(last_column_letter, last_row, sum_last_row_name) # generate the formula for the sum cell
    print(formula)

    new_worksheet[sum_cell_name].formula=formula # set the formula for the sum cell
    new_worksheet.autofit() # autofit the table
new_wb.save(os.path.join(path, 'purchase_order_new.xlsx')) # save the new workbook
new_wb.close() # close the new workbook
wb.close() # close the original workbook
app.quit() # quit the Excel instance
print("done")







